import { useState } from "react";
import PageHeader from "@/components/PageHeader";
import { demoConsultingRun, demoSocialRun, demoResearchRun } from "@/lib/data";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { Download, FileText } from "lucide-react";
import {
  LineChart, Line, BarChart, Bar, XAxis, YAxis, Tooltip,
  ResponsiveContainer, CartesianGrid, RadarChart, Radar,
  PolarGrid, PolarAngleAxis, PolarRadiusAxis, Cell, Legend
} from "recharts";

const barColors = [
  "hsl(var(--chart-1))", "hsl(var(--chart-2))", "hsl(var(--chart-3))",
  "hsl(var(--chart-4))", "hsl(var(--chart-5))", "hsl(var(--muted-foreground))",
];

export default function ReportsPage() {
  const [tab, setTab] = useState("graphs");

  const radarData = demoConsultingRun.results.initiatives.map(i => ({
    name: i.name.split(' ').slice(0, 2).join(' '),
    impact: i.impact === 'high' ? 90 : i.impact === 'medium' ? 60 : 30,
    effort: i.effort === 'high' ? 90 : i.effort === 'medium' ? 60 : 30,
  }));

  const clusterData = demoResearchRun.clusters.map(c => ({
    name: c.label,
    size: c.size,
    sentiment: Math.round(c.sentiment * 100),
  }));

  const report = `# VikingSwarm Studio v5 — Executive Report

## Nordic Market Entry Strategy

### Key Findings
${demoConsultingRun.results.rationale}

### ROI Projections
- **Baseline:** ${demoConsultingRun.results.roi.mid}x ROI
- **Upside:** ${(demoConsultingRun.results.roi.high * 1.4).toFixed(1)}x ROI
- **Downside:** ${(demoConsultingRun.results.roi.low * 0.6).toFixed(1)}x ROI

### Social Simulation Summary
- Final Sentiment: ${Math.round(demoSocialRun.results.finalSentiment * 100)}% positive
- Reach: ${(demoSocialRun.results.reach / 1000).toFixed(1)}K
- Viral Moments: ${demoSocialRun.results.viralMoments}

### Research Clusters
${demoResearchRun.clusters.map(c => `- **${c.label}**: ${c.size} responses (${c.sentiment > 0 ? '+' : ''}${Math.round(c.sentiment * 100)}% sentiment)`).join('\n')}

### Accepted Initiatives
${demoConsultingRun.results.initiatives.filter(i => i.status === 'accepted').map(i => `- ${i.name}: ${i.description}`).join('\n')}

---
*Generated by VikingSwarm Studio v5*
`;

  return (
    <div className="p-4 md:p-8 max-w-5xl mx-auto">
      <PageHeader
        title="Reports & Graphs"
        subtitle="Consolidated analysis and visual explorer"
        action={
          <Button size="sm" variant="outline" onClick={() => {
            const blob = new Blob([report], { type: 'text/markdown' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url; a.download = 'vikingswarm-report.md'; a.click();
          }}>
            <Download className="h-4 w-4 mr-1" /> Export
          </Button>
        }
      />

      <Tabs value={tab} onValueChange={setTab}>
        <TabsList className="grid w-full grid-cols-2 mb-6">
          <TabsTrigger value="graphs">Graph Explorer</TabsTrigger>
          <TabsTrigger value="report">Report Viewer</TabsTrigger>
        </TabsList>

        <TabsContent value="graphs">
          {/* Initiative Radar */}
          <section className="mb-8">
            <h2 className="font-display text-sm font-semibold mb-4">Initiative Impact vs Effort</h2>
            <div className="rounded-xl border border-border bg-card p-4">
              <ResponsiveContainer width="100%" height={300}>
                <RadarChart data={radarData}>
                  <PolarGrid stroke="hsl(var(--border))" />
                  <PolarAngleAxis dataKey="name" tick={{ fontSize: 10 }} stroke="hsl(var(--muted-foreground))" />
                  <PolarRadiusAxis tick={{ fontSize: 10 }} stroke="hsl(var(--muted-foreground))" />
                  <Radar name="Impact" dataKey="impact" stroke="hsl(var(--chart-1))" fill="hsl(var(--chart-1))" fillOpacity={0.3} />
                  <Radar name="Effort" dataKey="effort" stroke="hsl(var(--chart-2))" fill="hsl(var(--chart-2))" fillOpacity={0.2} />
                  <Legend wrapperStyle={{ fontSize: '12px' }} />
                </RadarChart>
              </ResponsiveContainer>
            </div>
          </section>

          {/* Social Timeline */}
          <section className="mb-8">
            <h2 className="font-display text-sm font-semibold mb-4">Social Sentiment Over Time</h2>
            <div className="rounded-xl border border-border bg-card p-4">
              <ResponsiveContainer width="100%" height={260}>
                <LineChart data={demoSocialRun.timeline}>
                  <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
                  <XAxis dataKey="round" tick={{ fontSize: 11 }} stroke="hsl(var(--muted-foreground))" />
                  <YAxis tick={{ fontSize: 11 }} stroke="hsl(var(--muted-foreground))" />
                  <Tooltip contentStyle={{ backgroundColor: 'hsl(var(--card))', border: '1px solid hsl(var(--border))', borderRadius: '8px', fontSize: '12px' }} />
                  <Legend wrapperStyle={{ fontSize: '12px' }} />
                  <Line type="monotone" dataKey="positive" stroke="hsl(var(--success))" strokeWidth={2} dot={false} />
                  <Line type="monotone" dataKey="negative" stroke="hsl(var(--destructive))" strokeWidth={2} dot={false} />
                  <Line type="monotone" dataKey="viral" stroke="hsl(var(--chart-5))" strokeWidth={2} dot={false} />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </section>

          {/* Research Clusters */}
          <section>
            <h2 className="font-display text-sm font-semibold mb-4">Research Cluster Sizes</h2>
            <div className="rounded-xl border border-border bg-card p-4">
              <ResponsiveContainer width="100%" height={260}>
                <BarChart data={clusterData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
                  <XAxis dataKey="name" tick={{ fontSize: 9 }} stroke="hsl(var(--muted-foreground))" angle={-20} textAnchor="end" height={60} />
                  <YAxis tick={{ fontSize: 11 }} stroke="hsl(var(--muted-foreground))" />
                  <Tooltip contentStyle={{ backgroundColor: 'hsl(var(--card))', border: '1px solid hsl(var(--border))', borderRadius: '8px', fontSize: '12px' }} />
                  <Bar dataKey="size" radius={[4, 4, 0, 0]}>
                    {clusterData.map((_, i) => (
                      <Cell key={i} fill={barColors[i % barColors.length]} />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </div>
          </section>
        </TabsContent>

        <TabsContent value="report">
          <div className="rounded-xl border border-border bg-card p-5">
            <div className="flex items-center gap-2 mb-4">
              <FileText className="h-4 w-4 text-gold" />
              <span className="font-display text-sm font-semibold">Executive Report</span>
            </div>
            <div className="prose prose-sm max-w-none dark:prose-invert">
              {report.split('\n').map((line, i) => {
                if (line.startsWith('# ')) return <h1 key={i} className="font-display text-xl font-bold mt-4 mb-2">{line.slice(2)}</h1>;
                if (line.startsWith('## ')) return <h2 key={i} className="font-display text-lg font-semibold mt-6 mb-2">{line.slice(3)}</h2>;
                if (line.startsWith('### ')) return <h3 key={i} className="font-display text-sm font-semibold mt-4 mb-1">{line.slice(4)}</h3>;
                if (line.startsWith('- **')) return <p key={i} className="text-sm ml-4 my-0.5" dangerouslySetInnerHTML={{ __html: line.slice(2).replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>') }} />;
                if (line.startsWith('- ')) return <p key={i} className="text-sm ml-4 my-0.5">• {line.slice(2)}</p>;
                if (line.startsWith('---')) return <hr key={i} className="my-4 border-border" />;
                if (line.startsWith('*')) return <p key={i} className="text-xs text-muted-foreground italic mt-2">{line.replace(/\*/g, '')}</p>;
                if (line.trim() === '') return <div key={i} className="h-2" />;
                return <p key={i} className="text-sm leading-relaxed">{line}</p>;
              })}
            </div>
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
}
